apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: andrej-booking
  namespace: ambulance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: andrej-booking
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # avoid flapping
